gdalle/SparseMatrixColorings.jl

- Project.toml
- docs/src/api.md
- src/SparseMatrixColorings.jl
- src/decompression.jl
- test/coloring_correctness.jl
- test/decompression_correctness.jl
**Compat**
- Bump version to 0.2.1
- Add `"<0.0.1"` to stdlib compat bounds in order to support Pkg operations in the test suite
**Source**
- Implement decompression (slowly) for general matrices
**Test**
- Test decompression for `Matrix` and not just `SparseMatrixCSC`
**Doc**
- Add `color_groups` to the API
> Add some functionality to the API

- Project.toml
- src/decompression.jl
- test/decompression_correctness.jl
- test/runtests.jl
**Compat**
- Bump version to 0.3.1
**Source**
- Replace `@views` with `view` and split lines for easier debugging
- Add `nnz` equality check between `A` and `S` (proxy for whole sparsity structure)
**Tests**
- Add small controlled tests
> More tests

- src/decompression.jl
- test/decompression_correctness.jl
**Source**
- Add better sparsity pattern comparison by validating `nzrange` (`rowvals` still could differ)
**Tests**
- Test exception thrown
> Better sparsity pattern check

- Project.toml
- docs/src/api.md
- src/SparseMatrixColorings.jl
- src/check.jl
- src/decompression.jl
- src/groups.jl
- src/matrices.jl
- test/check.jl
- test/coloring_correctness.jl
- test/decompression_correctness.jl
- test/matrices.jl
- test/runtests.jl
**Compat**
- Bump version to 0.3.2
**Source**
- Make a new file `matrices.jl` for `respectful_similar`, `same_sparsity_pattern`
- Create `matrix_versions(A)` which lists dense and sparse versions of `A`, with or without `Transpose/Adjoint/Symmetric`
- Simplify checks with `color_groups` and add more precise warnings
- Implement `decompress_symmetric` naively for dense matrices
**Tests**
- Test everywhere on the cartesian product of `matrix_versions(A)` and `matrix_versions(S)`
> Start symmetric decompression

- README.md
- src/coloring.jl
- src/matrices.jl
- test/coloring_correctness.jl
**Source**
- In star coloring, initialize `first_neighbors` by filling it with `(0, 0)`
**Tests**
- Add more random tests so that bugs will be caught with higher probability (the one introduced by #11 was not detected in the PR CI, only on main)
**Docs**
- Correct installation instruction in the README
> Fix bug + more robust tests

- test/Project.toml
- test/colpack.jl
- test/runtests.jl
**Tests**
Add comparison with the results of ColPack through ColPack.jl.
For the natural vertex ordering, the vector of colors should be exactly the same.
> Add comparison with ColPack to tests

- .github/workflows/Test.yml
- Project.toml
- src/SparseMatrixColorings.jl
- Bump version to v0.3.4
**Source**
- For `GreedyColoringAlgorithm` and the re-exports from ADTypes.jl, remove the `public` annotation since they are already exported
> Remove public when export is there

- Project.toml
- docs/src/api.md
- src/SparseMatrixColorings.jl
- src/adtypes.jl
- src/coloring.jl
- src/decompression.jl
- test/random.jl
**Version**
- Bump to v0.3.4
**Source**
- Implement `star_coloring_detailed` and `symmetric_coloring_detailed`, which return a `StarSet` in addition to the color vector
- Add methods to `decompress_symmetric` and `decompress_symmetric!` which take into account the `StarSet`
**Tests**
- Test the correctness of the new decompression on random instances
> Implement clever symmetric decompression with star set

- Project.toml
- docs/src/api.md
- src/SparseMatrixColorings.jl
- src/decompression.jl
**Version**
- Bump to v0.3.5
**Source**
- Factor out a `symmetric_coefficient` function which tells us where to find the value of `A[i, j]` in `B`. This function is faster when a `StarSet` is provided.
**Doc**
- Add `symmetric_coefficient` to the public API
- Fix the docstring typo spotted in #26
> Factor out `symmetric_coefficient`

- Project.toml
SparseMatrixColorings imports `stack` from Compat.jl:
https://github.com/gdalle/SparseMatrixColorings.jl/blob/83a1330a025ba2c45b95e144c388380ffec1ace1/src/SparseMatrixColorings.jl#L10
This has only been introduced in versions `3.46.0` and `4.2.0`:
https://github.com/JuliaLang/Compat.jl/blob/f8af0d15a6d8edbbddbae9a7841e38ea518a734f/README.md?plain=1#L95
> Update Compat.jl bounds for `stack`

- .github/workflows/Test.yml
**DI**
- For LTS tests, downgrade compat bounds to the earliest supported version of every dependency
> Downgrade compat in CI

- docs/src/api.md
- src/interface.jl
**Source**
- Make `ADTypes.some_coloring` standalone instead of calling `SMC.some_coloring_detailed`
> Remove preparation to speed up ADTypes interface

- docs/src/api.md
- src/SparseMatrixColorings.jl
- src/coloring.jl
- src/decompression.jl
- src/interface.jl
- src/result.jl
- src/sparsematrixcsc.jl
- test/performance.jl
- test/random.jl
- test/small.jl
> Introduce ColoringProblem

- src/SparseMatrixColorings.jl
- test/Project.toml
- test/colpack.jl
- test/performance.jl
- test/random.jl
- test/small.jl
- test/suitesparse.jl
- Remove re-exports of `column_coloring`, `row_coloring` and `symmetric_coloring`
- Adjust tests
> Don't export ADTypes interface

- src/decompression.jl
We know that diagonal coefficients of `A` are not combined with other coefficients in the compressed matrix `B`.
`T` can have less columns thanks to that.
I also fixed a comment, we store the lower triangular of `A` and not its upper triangular part.
> Improve the decompression for acyclic coloring

- docs/make.jl
- docs/src/api.md
- docs/src/dev.md
- src/SparseMatrixColorings.jl
- test/performance.jl
- test/small.jl
- Export `decompress` and `decompress!`
- Split API reference between a public and a private page (called "dev docs")
> Export decompress and split API docs

- docs/src/dev.md
- src/decompression.jl
- src/interface.jl
- src/result.jl
- src/sparsematrixcsc.jl
- test/small.jl
- Create two variants of `DefaultColoringResult` for direct and indirect symmetric decompression, named `StarSetColoringResult` and `TreeSetColoringResult` respectively
- Make sure that `DefaultColoringResult` and its variants are all tested
> Implement StarSetColoringResult and TreeSetColoringResult

- docs/src/api.md
- src/SparseMatrixColorings.jl
- src/decompression.jl
- test/random.jl
- test/small.jl
- Implement `B = compress(A, result)` which is undone by `A = decompress(B, result)`
- Add doctests to the `compress`, `decompress` and `decompress!` functions
- Use `compress` in tests
> Implement `compress`

- src/decompression.jl
- src/interface.jl
- src/result.jl
- Allow `compress` to return a tuple `(Br, Bc)` instead of a single `B` when the partition is `:bidirectional`
- Make the type parameters of `AbstractColoringResult` part of the public API
- Improve docstrings
> Generalize the API to enable bicoloring

- src/decompression.jl
- test/utils.jl
@gdalle The optimized version of the acyclic coloring is finally working! :muscle: 
I was able to verify it on this example:
```julia
using SparseMatrixColorings
A = Float64[
1  2  0  0  0  0  3  0  0  0
2  4  5  0  6  0  0  0  0  0
0  5  7  8  0  9  0  0  0  0
0  0  8  10 0  0  0  0  0  11
0  6  0  0  12 13 0  14 0  0
0  0  9  0  13 15 0  0  16 0
3  0  0  0  0  0  17 18 0  0
0  0  0  0  14 0  18 19 20 0
0  0  0  0  0  16 0  20 21 22
0  0  0  11 0  0  0  0  22 23
] |> sparse
g = SparseMatrixColorings.Graph(A - Diagonal(A))
order = SparseMatrixColorings.NaturalOrder()
colors, tree_set = SparseMatrixColorings.acyclic_coloring(g, order)
result = coloring(
A,
ColoringProblem(;
structure=:symmetric, partition=:column, decompression=:substitution
),
GreedyColoringAlgorithm(),
) …
```
> Implement `TreeSet`-based acyclic decompression

- src/SparseMatrixColorings.jl
- src/coloring.jl
- src/decompression.jl
- src/result.jl
Related to #68 
- Efficient implementation of `TreeSetColoringResult`
> More optimization for the decompression of the acyclic coloring

- src/decompression.jl
- test/performance.jl
- Avoid `findnz` and directly use the `SparseMatrixCSC` structure of `S` to iterate over all nonzero `(i, j)` pairs in decompression
- Un-skip the tests for alloc-free decompression into `A::Matrix`
> Allocation-free decompression in all cases

- docs/src/api.md
- docs/src/dev.md
- src/SparseMatrixColorings.jl
- src/decompression.jl
- src/interface.jl
- src/matrices.jl
- test/constructors.jl
- test/matrices.jl
- test/runtests.jl
- Make `ColoringProblem{structure,partition}()` and `GreedyColoringAlgorithm{decompression}(order)` part of the public API. Document that the other constructors (based on keyword arguments) are type-unstable. Add a few more consistency checks for these constructors.
- Export the names `NaturalOrder`, `RandomOrder` and `LargestFirst`.
- Remove `decompress_aux!` so that the various methods for `decompress!` are visible to users.
> Make type-stable constructors part of the API

- src/decompression.jl
- test/random.jl
- test/small.jl
- test/utils.jl
> Add option to decompress into a triangle only

- src/decompression.jl
- test/utils.jl
- Replace the default value of `uplo` with `:F`, which is apparently common in numerical linear algebra.
> Replace `:UL` with `:F` to select a triangle

- src/decompression.jl
- Add a warning to the docstring of `decompress_single_color!` that it won't work for `:substitution`. As stated in #86, I believe that it is a general restriction.
> Warn that single-color decompression is for direct coloring only

- src/examples.jl
- src/result.jl
- test/utils.jl
- Bring the `eltype` of small examples back to `Int` and set `decompression_eltype=Float64` in `test/utils.jl`, in order to observe a buffer type mismatch.
- Debug `LinearSystemColoringResult`
> Bringe coverage to 100%

- src/decompression.jl
- Modify `decompress!(A, B, result, uplo)` so that the sparsity patterns of `A` and `S` are only compared when `uplo == :F`
> Only check sparsity pattern equality when `uplo == :F`

- src/decompression.jl
- test/allocations.jl
- test/type_stability.jl
- test/utils.jl
- The previous version assumed that the sparsity patterns of `S` and `A` were aligned. If `A` is just one of the triangles, we need to count its indices separately to map them onto `compressed_indices`.
- Adjust tests to decompress into `similar(triu(A))` instead of `similar(A)`
> Fix star decompression into `SparseMatrixCSC` triangle

- src/result.jl
- Use a more efficient `queue` in `TreeSetResult`.
> Use a more efficient `queue` in `TreeSetResult`

- src/SparseMatrixColorings.jl
- src/matrices.jl
Modify `matrix_versions(A)` so that it also returns `Symmetric` and `Hermitian` versions when appropriate, built from the entire matrix `A` or from either triangle `LowerTriangular(A)` and `UpperTriangular(A)`. This allows testing on more kinds of inputs, including triangles.
#98 was effectively supported (as long as we wrap the triangle into `Symmetric`) but at least it is tested now. We will worry about performance at a later point.
> Add tests with `Symmetric` and `Hermitian` inputs

- src/SparseMatrixColorings.jl
- src/result.jl
Replace every occurrence of `I, J, _ = findnz(S)` with the non-allocating iteration:
```julia
rv = rowvals(S)
for j in axes(S, 2)
for k in nzrange(S, j)
i = rv[k]
end
end
```
> Get rid of inefficient `findnz`

- src/graph.jl
- src/interface.jl
- src/result.jl
When `A` is already a `SparseMatrixCSC`, calling `sparse(A)` makes a useless copy, while `convert(SparseMatrixCSC, A)` doesn't. The behavior in other cases seems identical.
> Replace `sparse(A)` with `convert(SparseMatrixCSC, A)`

- src/result.jl
@gdalle It seems that we have unexpected allocations in `ColumnResult` and `StarSetResult`.
I will investigate.
> Remove dynamic allocations in group_by_color

- docs/src/dev.md
- src/SparseMatrixColorings.jl
- src/coloring.jl
- src/decompression.jl
- src/graph.jl
- src/order.jl
- test/graph.jl
- test/suitesparse.jl
- Store size information in the `Graph` structure
- Define `nb_vertices` and `nb_edges` in lieu of `length` and `nnz` to avoid confusion
- Redefine `transpose_graph(::AbstractMatrix)` from #107 as `Base.transpose(::Graph)`
- Use a simpler implementation which does just one allocation too many (a new vector of `nzval`), instead of a custom handwritten loop (at least I think so)
- Add better transposition tests
> Improve graph structure a little bit

- src/graph.jl
- src/order.jl
- test/graph.jl
- test/order.jl
Start fixing #118 by correcting the `LargestFirst` order to take distance-2 degree into account.
Add some tests (we probably need more).
> Consider distance-2 degree for `LargestFirst` order in bipartite graph

- src/coloring.jl
- src/graph.jl
Bring back some of the clarity I had removed
> Rename variables `n -> nv` and `e -> ne`

- .gitignore
- docs/src/dev.md
- src/coloring.jl
- src/graph.jl
- src/interface.jl
- src/order.jl
- test/allocations.jl
- test/graph.jl
- test/order.jl
- test/suitesparse.jl
**Idea**
Create two clearly distinct graph structures (`AdjacencyGraph` and `BipartiteGraph`) and distinguish them from the container for the sparsity pattern.
**Benefits**
Now:
- Get rid of the weird `Graph{true}` / `Graph{false}` which wasn't even a graph in the rectangular case.
- Allow storing more stuff in the graph structure if we want (typically the number of edges as you suggested).
In the future:
- Gain flexibility to implement graphs based on different pattern types (for other structured matrices like banded), just by making the pattern fields parametric.
**Changes**
- Rename `Graph` into `SparsePatternCSC`, which is exactly a `SparseMatrixCSC` without `nzval`. Remove definitions of `neighbors` and friends, keep only linear algebra stuff there.
- Create a proper `AdjacencyGraph` …
> Clearly separate graphs from the sparsity pattern

- docs/src/api.md
- src/SparseMatrixColorings.jl
- src/constant.jl
- test/constant.jl
- test/runtests.jl
- Add a new `ConstantColoringAlgorithm` which always returns the same `ColumnColoringResult` or `RowColoringResult` (fix #124)
- Make sure it errors when it is used inappropriately (wrong type of coloring, wrong matrix shape)
- Document and test it properly
> Implement `ConstantColoringAlgorithm`

- src/decompression.jl
We also want the optimized version of `decompress!` for star coloring when the user specifies `uplo=:F` and not only when `uplo` is not specified.
> Merge two decompress! for star coloring

- src/constant.jl
- src/decompression.jl
- src/graph.jl
- src/interface.jl
- src/matrices.jl
- src/result.jl
- test/graph.jl
- test/utils.jl
Fix #126, fix #131
Before this PR, the `result` type would always store a `SparseMatrixCSC` and forget the initial matrix `A`. Now it stores both the initial matrix `A` and the `AdjacencyGraph` or `BipartiteGraph` used for coloring, which contains the sparse conversion. This has two main advantages:
- To prepare for row decompression we do not need to recompute a transpose, it is already done in the `BipartiteGraph`
- When decompressing out-of-place, we can instantiate `similar(A)` instead of `similar(S)`, which makes more sense and paves the way for structured matrices
I also remove some eltype constraints on `A` and `B` which were not necessary. For instance, if `eltype(B) == Float32` and `eltype(A) == Float64`, we can decompress from `B` to `A` without issue.
> Store graph in result to allow generic matrices

- Project.toml
- docs/src/api.md
- src/SparseMatrixColorings.jl
- src/result.jl
- test/random.jl
- test/suitesparse.jl
- test/utils.jl
- Bump version to v0.4.4
- Implement a function `sparsity_pattern` which returns exactly the matrix `A` that was given to the coloring algorithm. That way, @Vaibhavdixit02 and others won't have to rely on internals to retrieve it.
- Add this new function to `test/utils.jl` and move some code around there 
> [!NOTE]
> Until the next breaking version, this effectively imposes that the sparsity pattern should always be stored in the result type (which is true since #126)
> Add `sparsity_pattern` getter for results

- Project.toml
- src/coloring.jl
Make sure that there is no branch where `symmetric_coefficient` returns `nothing`.
This caused JET's type stability tests to fail on the pre-release version of Julia in https://github.com/gdalle/DifferentiationInterface.jl/pull/535
> Improve type stability in star set

- docs/src/dev.md
- src/coloring.jl
- src/graph.jl
- src/order.jl
- test/graph.jl
Revamp adjacency graphs so that we have two implementations:
```julia
AdjacencyGraph <: AbstractAdjacencyGraph
AdjacencyFromBipartiteGraph <: AbstractAdjacencyGraph
```
The second one efficiently represents the symmetric matrix `[0 A'; A 0]`
> Implement efficient adjacency graph from bipartite

- docs/src/dev.md
- src/decompression.jl
- src/graph.jl
- src/interface.jl
- src/result.jl
- test/graph.jl
- test/random.jl
- test/utils.jl
> [!NOTE]
> This PR is not about performance, it's about getting stuff to work and adding the necessary tests. We will worry about performance later.
- Fix a bug in `AdjacencyFromBipartiteGraph` (introduced in #144) where the neighbors didn't have the correct offset in the block structure.
- Define a type `BicoloringResult` which contains colors for both columns and rows, as well as a pointer to a `StarSetColoringResult`/`TreeSetColoringResult` associated with the big matrix `[0 A'; A 0]`.
- To go from column colors of `[0 A'; A 0]` to row and column colors of `A`, renumber from `1` on both sides. Example: if `size(A) = (3, 2)` and `color = [1, 2, 4, 3, 2]`, then `column_color = [1, 2, 3]` and `row_color = [2, 1]`. We lose the correspondence with the symmetric matrix, but we gain …
> Working prototype for bicoloring (coloring + decompression)

- .github/workflows/Test.yml
- Project.toml
- src/SparseMatrixColorings.jl
- src/coloring.jl
- src/constant.jl
- src/decompression.jl
Julia 1.11 was released today, and Julia 1.10 announced as the LTS version (see <https://julialang.org/downloads/>)
- Remove Compat.jl from dependencies
- Remove `lts` from CI
> Drop support for Julia 1.6

- src/decompression.jl
- src/result.jl
close #93
- Add the following method:
```julia
decompress!(A::SparseMatrixCSC{R}, B::AbstractMatrix{R}, result::TreeSetColoringResult, uplo::Symbol=:F)
...
end
```
> Decompression of acyclic coloring with SparseMatrixCSC

- docs/src/dev.md
- src/coloring.jl
- src/decompression.jl
- src/graph.jl
- src/interface.jl
- src/order.jl
- src/result.jl
- test/allocations.jl
- test/graph.jl
- test/random.jl
- test/type_stability.jl
- test/utils.jl
- Remove adjacency graph from bipartite introduced in #144 because we need an actual `SparseMatrixCSC` containing `A` and `Aᵀ` for efficient decompression.
- Precompute more stuff and allocate all necessary storage when creating a `BicoloringResult`.
- To decompress a `BicoloringResult` into a `SparseMatrixCSC`, actually decompress into a larger matrix `A_and_noAᵀ`, which contains the lower triangle of `A_and_Aᵀ`. This larger matrix shares the vector `A.nzval`, so that `A` is updated in-place.
- Add type stability and allocation tests for bicoloring. At the moment, only decompression into a `SparseMatrixCSC` is alloc-free. Decompression into a `Matrix` still requires taking the bottom left submatrix of `A_and_noAᵀ` (it also could be a view but views of sparse matrices are inefficient).
> Allocation-free bidirectional decompression

- Project.toml
- docs/src/vis.md
- ext/SparseMatrixColoringsColorsExt.jl
- src/check.jl
- src/coloring.jl
- src/decompression.jl
- src/interface.jl
- src/result.jl
- test/check.jl
- test/random.jl
- test/result.jl
- test/suitesparse.jl
- test/utils.jl
Fixes #122, fixes #158
**Done**:
1. mirroring the decompression code to detect which colors are needed
2. zero out unneeded colors
3. renumber colors to get a lower maximum color
-  Clarify the negative hub trick for star coloring, and undo it before building the `StarSet`
- Move the BFS computation for acyclic coloring from the result constructor to the `TreeSet` constructor, so that it is available for postprocessing
**To do:**
- Rectangle
- Arrowhead
> feat: allow neutral colors and postprocessing

- src/coloring.jl
We don't use it anymore after #166.
> Remove forest from the TreeSet

- src/coloring.jl
I wanted to use the function `sizehint!` in `DataStructures.jl` but it's incomplete:
https://github.com/JuliaCollections/DataStructures.jl/blob/master/src/disjoint_set.jl#L182-L186
We should do our own structure for the `forest` one day.
> Reduce the dynamic allocations in acyclic coloring

- .github/workflows/Benchmark.yml
- benchmark/Project.toml
- benchmark/benchmarks.jl
- Sum times on several random matrices instead of one
- Ensure reproducible randomness between runs
- Add benchmarks for bicoloring and bidirectional decompression
The benchmark results on this PR are still using the code from `main`
> Improve benchmarks, add bicoloring

- src/coloring.jl
- src/decompression.jl
- src/graph.jl
- src/interface.jl
- src/result.jl
close #182
Take into account that the diagonal is zero in bicoloring and could be zero in symmetric colorings for a faster postprocessing, decompression and construction of the `TreeSetColoringResult`.
> Add an attribute has_loops in AdjacencyGraph

- src/coloring.jl
- src/decompression.jl
- src/result.jl
This PR removes `vertices_by_tree` from the `TreeSet`.
This `Vector{Vector{Int}}` contains the list of vertices for each tree in the forest.  
It was previously used to reset the buffer during the decompression of the acyclic coloring.  
However, we can easily recover the vertices of a tree from the list of edges of the related tree (`reverse_bfs_orders`).
Since all edges of a tree are stored in the format `(leaf, parent)`, we can reset the buffer for all "leaves" plus the parent of the last edge, which corresponds to the root of the tree.
Other minor modifications:
- Specify the type of some arrays (`spokes`, `trees`, `reverse_bfs_orders`) to potentially help the compiler. I remember that JET was not happy for the following allocations in Krylov.jl …
> Remove vertices_by_tree for the acyclic coloring

- docs/src/dev.md
- src/graph.jl
- src/interface.jl
- test/graph.jl
close #161 
If we want to store exactly `[0 A'; A 0]`, we can't use `symmetric_pattern` to build `Aᵀ`.
```julia
Aᵀ = if symmetric_pattern || A isa Union{Symmetric,Hermitian}
A
else
transpose(A)
end
```
We will have the wrong nonzeros in `A_and_Aᵀ` (but the correct sparsity pattern).
I'm wondering if we should store a different matrix than `b = A_and_Aᵀ` in `StarSetResult` or `TreeSetResult`.  
If I remember correctly, we want to store `B` to have the correct type for the function `decompress`, but in this case, it’s always a `SparseMatrixCSC`, whereas `A` could have a different type.
We probably only want the `AdjacencyGraph` of `A_and_Aᵀ` and not the matrix itself, and we could likely achieve this with a keyword argument for `AdjacencyGraph` or another constructor that takes two …
> Improve how we build A_and_Aᵀ

- src/decompression.jl
- src/result.jl
- test/allocations.jl
close #181 
Should be merged after #180.
> Check if a buffer for the decompression of acyclic coloring is needed

- docs/Project.toml
- docs/src/vis.md
- ext/SparseMatrixColoringsColorsExt.jl
- src/show_colors.jl
- test/show_colors.jl
> viz: split row and column colors in bicoloring visualization

- src/coloring.jl
- src/decompression.jl
- src/result.jl
close #172 
- Avoid the call to remap_colors in postprocess!
- Optimize `remap_colors`
- Use two vectors of integer `symmetric_to_column` and `symmetric_to_row` for the mapping between symmetric colors and row / column colors
> Optimize remap_colors

- benchmark/benchmarks.jl
- Decompression benchmarks used to be for a `Bool`-valued matrix, which prevents caching of decompression memory since the default setting is `decompression_eltype=Float64`
> Predict correct eltype in decompression benchmarks

- docs/src/api.md
- src/SparseMatrixColorings.jl
- src/interface.jl
- test/small.jl
- test/utils.jl
- Add a function `fast_coloring` which directly returns the vector(s) of colors, without laying the groundwork for decompression
> Implement fast coloring without decompression prep

- src/coloring.jl
- src/decompression.jl
- test/allocations.jl
close #178, #181
Add a vector of booleans `is_star` to the `TreeSet` so that we can enable more efficient post-processing for acyclic coloring by determining if a tree is a star (trivial or non-trivial).
> Detect stars in the forest for acyclic coloring

- test/runtests.jl
`SMC.jl` requires at least Julia 1.10 now.
> Update runtests.jl for Julia >= 1.10

- src/decompression.jl
Use `compressed_indices` from the `StarColoringResult`.
> Improve the decompression of star coloring for AbstractMatrix

- src/coloring.jl
- src/interface.jl
- test/suitesparse.jl
I checked something a few days with `@code_warntype` and I found that the compiler generated a very complex code to handle the lack of default value for the keyword argument.
It could also be an argument.
> Add a default value for postprocessing

- src/coloring.jl
- src/decompression.jl
It removes the need for the vector `spokes`.
> Update decompression_single_color! for star coloring

- src/adtypes.jl
- src/check.jl
- src/coloring.jl
- src/constant.jl
- src/decompression.jl
- src/graph.jl
- src/interface.jl
- src/order.jl
- src/result.jl
- test/graph.jl
- test/type_stability.jl
The idea is that if we propagate integer types carefully, we could store all indices in `Int32` whenever that is enough, leading to a 2x reduction of memory footprint.
Caveats:
- Just because an integer type `T` is able to store the vector of colors doesn't mean it is able to store every vertex.
- As a result, I use separate integer types for indices (often called `T1`) and colors (often called `T2`)
Still a draft, don't merge yet because I fear this might make some existing code error. Also needs tests on `Int32` indices.
> Propagate arbitrary integer types as indices

- src/order.jl
Adjust docstrings for ColPack orders, following #229
> Remove warnings on ColPack orders

- src/result.jl
Note that we already don't store the `TreeSet` in `TreeSetColoringResult`.
> Remove StarSet from the StarSetColoringResult

- src/coloring.jl
- src/decompression.jl
- src/forest.jl
- src/result.jl
- test/forest.jl
Improve the readability of what was done in #228.
I found that the need to update a variable `first` in various specific places (at the end of for loops) in the code was quite difficult to read and error-prone.
Things will become even more complex with #233, so I prefer to make these modifications first.
> Replace num_edges_per_tree by tree_edge_indices in TreeSet

- src/graph.jl
- src/order.jl
- test/order.jl
- Speed up degree computation in adjacency graphs with a diagonal
- Compute the degree of each vertex once and store it before sorting
- Avoid `fill!(visited, false)` in other places when only some coefficients have been set to `true`
> Speed up LargestFirst order

- src/coloring.jl
- src/decompression.jl
- src/forest.jl
- test/allocations.jl
The code is not yet documented but we can have an idea of the gain.
> Remove the dictionaries in TreeSet

- benchmark/benchmarks.jl
No need to run benchmarks on this one since the test cases are defined on main, we can merge right away if it looks ok
> Add ordering benchmarks

- src/order.jl
- update how we use `visited` vertices to more efficiently reset the vector `visited`.
- Don't use `pushfirst!`.
- Don't allocate two vectors `degrees_dist2` / `degrees` or `true_degrees` / `degrees`. We only need to store one of them.
Quick test for `pushfirst!` vs `push!`
```julia
function bob1(a::Vector{Int}, n)
for k = 1:n
push!(a, k)
end
end
function bob2(a::Vector{Int}, n)
for k = 1:n
pushfirst!(a, k)
end
end
n = 100000
a = Int[]
sizehint!(a, n)
timer1 = @elapsed bob1(a, n)
a = Int[]
sizehint!(a, n)
@allocated bob1(a, n)
a = Int[]
sizehint!(a, n)
timer2 = @elapsed bob2(a, n)
a = Int[]
sizehint!(a, n)
@allocated bob2(a, n)
println("pushfirst! is slower than push! by a factor: ", timer2 / timer1)
```
> More efficient reset of visited vertices in order.jl

- Project.toml
- src/SparseMatrixColorings.jl
- src/precompile.jl
This speeds up time-to-first-plot tremendously.
Benchmark (to run in a fresh Julia session):
```julia
using LinearAlgebra, Random, SparseArrays
using SparseMatrixColorings
@time begin
A = sprand(MersenneTwister(0), Bool, 10, 10, 0.2)
problem = ColoringProblem(; structure=:nonsymmetric, partition=:column)
algo = GreedyColoringAlgorithm(; decompression=:direct)
result = coloring(A, problem, algo)
B = compress(A, result)
decompress(B, result)
end;
@time begin
A = sprand(MersenneTwister(0), Bool, 10, 10, 0.2)
problem = ColoringProblem(; structure=:nonsymmetric, partition=:bidirectional)
algo = GreedyColoringAlgorithm(; decompression=:substitution, postprocessing=true)
result = coloring(A, problem, algo)
Br, Bc = compress(A, result)
decompress(Br, Bc, result)
end;
```
With precompilation:
- …
> Add precompilation workload
